### ISSUE TITLE
Negative selectors

### ISSUE THREAD

**Issue by benmatselby** [kevinweber/inline-comments#1]
Not sure where you would like feature requests, but it would be handy if the selectors section could use negative selectors.

If it can do this, I seem to be struggling.

Use case, is display inline commenting on all pages, except a page with a certain tag for example.

**Comment by kevinweber** [comment]
Every selector that can be used using jQuery should be possible. Try something like
`.single:not(.postid-135) p`

**Comment by benmatselby** [comment]
Aye, very true.. I didn't write the :not correctly.. Thanks for responding.
