### ISSUE TITLE
Selection (in JS) for empty elements

### ISSUE THREAD

**Issue by Herdo** [kevinweber/inline-comments#9]
I have the a post as shown on the image below:
![grafik](https://user-images.githubusercontent.com/651191/27741778-834c6136-5db6-11e7-9ff2-374a2f213745.png)

As `Selectors` I have defined `.entry-content p` - nothing else.
Asy you can see, the comment bubbles are correctly generated for empty paragraphs.

I searched for a solution, but I was unable to find a pure CSS solution to solve this problem.
Would it be possible to hook into the bubble generation in JS (maybe with an additional option for the settings, or always enabled), to exclude the bubble generation for elements that match the selectors, but are empty?

**Comment by Herdo** [comment]
Note:
The elements are not really empty, they may include a `new line`, `tabs` or `whitespaces`.
The rule above should still apply.

**Comment by kevinweber** [comment]
Hi @Herdo, thanks for bringing up this issue. There might be cases for some websites where an empty paragraph should display a comment bubble. So I don't plan on implementing your suggested feature.

One solution is to get rid of your empty `<p>` tags and adjust the theme's CSS in some way so it generates your spaces/margins.
